# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36e814831d960dc5e308ff54a4ca68590a79ff73f3fb00ccddf05dc0aaa1c536221a24a52a587074e0feaab0d090f30fd0c94a1dfb8f4d9224125c965c0c87f6

test:
  secret_key_base: 23147d519990143e2de06de4d9143d3c45c931a76ebd91da564707ef7ee807ec5689c70335082f34e2ae4e14a85713a990339b312a60251a08bc1400d9e2883e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
